apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-tentacle.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-tentacle.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-role" (include "kubernetes-tentacle.serviceAccountName" .) }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["*"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-binding" (include "kubernetes-tentacle.serviceAccountName" .) }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-tentacle.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ printf "%s-role" (include "kubernetes-tentacle.serviceAccountName" .) }}
  apiGroup: rbac.authorization.k8s.io