{{- if .Values.tentacle.listeningPort -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-tentacle.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-tentacle.labels" . | nindent 4 }}
spec:
  type: "LoadBalancer"
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "kubernetes-tentacle.selectorLabels" . | nindent 4 }}
{{- end }}
