{{- $isNfsEnabled := (not (or .persistence.storageClassName .persistence.volumeName)) -}}
persistence:
  {{/* This isn't strictly necessary, but we want to make it clear for NFS this is set */}}
  {{- if $isNfsEnabled }}
  accessModes: ["ReadWriteMany"]
  {{- end}}
  nfs:
    enabled: {{ $isNfsEnabled}}