apiVersion: agent.octopus.com/v1beta1
kind: ScriptPodTemplate
metadata:
  labels:
    app.kubernetes.io/name: crd-gen
    app.kubernetes.io/managed-by: kustomize
  name: scriptpodtemplate-sample
spec:
  # TODO(user): Add fields here
