#!/bin/zsh

# This script modifies the generated CRD file to remove fields that are unnecessary or problematic from the coreV1 types
# It should be run after the CRD has been generated by kubebuilder
# Usage: ./crd.sh <path-to-crd-file>

if [ $# -eq 0 ]; then
    echo "Usage: $0 <path-to-crd-file>"
    exit 1
fi

CRD_FILE="$1"

if [ ! -f "$CRD_FILE" ]; then
    echo "Error: File '$CRD_FILE' does not exist"
    exit 1
fi

# Remove unnecessary fields from podSpec in the CRD's openAPIV3Schema
yq eval 'del(.spec.versions[].schema.openAPIV3Schema.properties.spec.properties.podSpec.properties.containers)' -i "$CRD_FILE"
yq eval 'del(.spec.versions[].schema.openAPIV3Schema.properties.spec.properties.podSpec.required)' -i "$CRD_FILE"
yq eval 'del(.spec.versions[].schema.openAPIV3Schema.properties.spec.properties.podSpec.properties.initContainers)' -i "$CRD_FILE"
yq eval 'del(.spec.versions[].schema.openAPIV3Schema.properties.spec.properties.podSpec.properties.ephemeralContainers)' -i "$CRD_FILE"

echo "Successfully removed fields from $CRD_FILE"
