apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-agent.autoUpgraderClusterRoleName" . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]