{{- if .Values.scriptPods.serviceAccount.useNamespacedRoles }}
{{- $autoUpgraderSelfRoleName := include "kubernetes-agent.autoUpgraderSelfRoleName" . -}}
{{- $autoUpgraderTargetRoleName := include "kubernetes-agent.autoUpgraderTargetRoleName" . -}}
{{- $targetNamespaces := include "kubernetes-agent.targetNamespaces" . | fromJsonArray -}}

# Role for managing the agent in its own namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $autoUpgraderSelfRoleName }}
  namespace: {{ .Release.Namespace | quote }}
rules:
{{- $overrideRules := include "kubernetes-agent.renderRbacRules" (dict "rules" .Values.autoUpgrader.selfNamespaceRoleRules "name" "autoUpgrader.selfNamespaceRoleRules") }}
{{- if $overrideRules }}
{{ $overrideRules | nindent 2 }}
{{- else }}
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}

{{- if not (empty $targetNamespaces) }}
# Roles for managing script pod roles/rolebindings in target namespaces
{{- range $targetNamespace := $targetNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $autoUpgraderTargetRoleName }}
  namespace: {{ $targetNamespace | quote }}
rules:
{{- $overrideRules := include "kubernetes-agent.renderRbacRules" (dict "rules" $.Values.autoUpgrader.targetNamespaceRoleRules "name" "autoUpgrader.targetNamespaceRoleRules") }}
{{- if $overrideRules }}
{{ $overrideRules | nindent 2 }}
{{- else }}
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  {{/* escalate verb allows granting permissions in Roles beyond what the auto-upgrader itself holds */}}
  verbs: ["escalate"]
{{- end }}
{{- end }}
{{- end }}
{{- end }}