apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-agent.autoUpgraderServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
automountServiceAccountToken: true