{{- if .Values.storage.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs.pvcName" . }} 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.nfs.size}}
  storageClassName: {{ include "nfs.storageClassName" . }} 
{{- end }}