{{- if and .Values.persistence.storageClassName .Values.persistence.customPersistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: {{ .Values.persistence.customPersistentVolume.csi.driver }}
  name: {{ include "kubernetes-agent.pvName" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- with .Values.persistence.customPersistentVolume.mountOptions }}
  mountOptions:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  claimRef:
    name: {{ include "kubernetes-agent.pvcName" . }}
    namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.persistence.customPersistentVolume.csi }}
  csi:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
