{{- if not .Values.persistence.storageClassName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs.pvcName" . }} 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
  volumeName: {{ include "nfs.pvName" . }}
  storageClassName: {{ include "nfs.storageClassName" . }} 
{{- end }}