apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs.basePvcName" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.nfs.size }}