{{- if not (include "kubernetes-agent.useCustomPvc" .) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs.pvcName" . }} 
spec:
  accessModes:
    {{- .Values.persistence.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
  volumeName: {{ include "nfs.pvName" . }}
  storageClassName: {{ include "nfs.storageClassName" . }} 
{{- end }}