apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-agent.podServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.podServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true