{{- if  and (empty .Values.scriptPods.serviceAccount.targetNamespaces) (not .Values.agent.worker.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include "kubernetes-agent.scriptPodClusterRoleBindingName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-agent.scriptPodServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubernetes-agent.scriptPodClusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}