apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-agent.scriptPodServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.scriptPods.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true