apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-agent.podClusterRoleName" . }}
rules:
{{- if .Values.podServiceAccount.clusterRole.rules}}
{{ .Values.podServiceAccount.clusterRole.rules | toYaml| nindent 2 }}
{{- else }}
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
{{- end }}