{{- if .Values.agent.certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.preinstall.secrets.certificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "kubernetes-agent.hookAnnotationsWithSuccessDelete" . | nindent 4 }}
type: Opaque
data:
  certificate: {{ .Values.agent.certificate | b64enc }}
{{- end}}