apiVersion: v1
kind: Secret
metadata:
  name: tentacle-secret-pre
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "kubernetes-agent.defaultHookAnnotations" . | nindent 4 }}