{{- if (include "kubernetes-agent.serverCertificate.certificate" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: octopus-server-certificate-pre
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "kubernetes-agent.hookAnnotationsWithSuccessDelete" . | nindent 4 }}
data:
  octopus-server-certificate.pem: {{ (include "kubernetes-agent.serverCertificate.certificate" .) | b64dec | quote }}
{{- end }}