apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-binding" (include "kubernetes-agent.preinstall.serviceAccountName" .) }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "kubernetes-agent.hookAnnotationsWithSuccessDelete" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-agent.preinstall.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ printf "%s-role" (include "kubernetes-agent.preinstall.serviceAccountName" .) }}
  apiGroup: rbac.authorization.k8s.io