{{- if .Values.agent.serverCertificate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: octopus-server-certificate-pre
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "kubernetes-agent.hookAnnotationsWithSuccessDelete" . | nindent 4 }}
data:
  octopus-server-certificate.pem: {{ .Values.agent.serverCertificate | b64dec | quote }}
{{- end }}