{{- if .Values.scriptPods.disruptionBudgetEnabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: script-pod-disruption-budget
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 8888
  selector:
    matchExpressions:
    - { key: octopus.com/scriptTicketId, operator: Exists }
{{- end }}
