{{- if .Values.scriptPods.disruptionBudgetEnabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-script-pdb" (include "kubernetes-agent.fullName" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 8888
  selector:
    matchExpressions:
    - { key: octopus.com/scriptTicketId, operator: Exists }
{{- end }}
