{{- if .Values.agent.certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.secrets.certificate" . }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  certificate: {{ .Values.agent.certificate | b64enc }}
{{- end}}