{{- if (include "kubernetes-agent.serverCertificate.certificate" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: octopus-server-certificate
  namespace: {{ .Release.Namespace | quote }}
data:
  octopus-server-certificate.pem: {{ (include "kubernetes-agent.serverCertificate.certificate" .) | b64dec | quote }}
{{- end }}