apiVersion: v1
kind: ConfigMap
metadata:
  name: tentacle-metrics
  namespace: {{ .Release.Namespace | quote }}
{{- with .Values.testing.tentacle.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end -}}
