apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.secrets.serverAuth" . }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
{{- with .Values.tentacle.bearerToken }}
  bearer-token: {{ . | b64enc }}
{{- end }}  
{{- with .Values.tentacle.serverApiKey }}
  api-key: {{ . | b64enc }}
{{- end }}