apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.secrets.serverAuth" . }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
{{- if and (not .Values.agent.bearerTokenSecretName) (not .Values.agent.serverApiKeySecretName) (not .Values.agent.usernamePasswordSecretName) }}
{{- with .Values.agent.bearerToken }}
  bearer-token: {{ . | b64enc }}
{{- end }}  
{{- with .Values.agent.serverApiKey }}
  api-key: {{ . | b64enc }}
{{- end }}
{{- with .Values.agent.username }}
  username: {{ . | b64enc }}
{{- end }}
{{- with .Values.agent.password }}
  password: {{ . | b64enc }}
{{- end }}
{{- end }}
{{- with .Values.agent.pollingProxy.password }}
  polling-proxy-password: {{ . | b64enc }}
{{- end }}