{{- if not .Values.persistence.nfs.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "kubernetes-agent.pvcName" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- .Values.persistence.accessModes | toYaml | nindent 4 }}
  {{- if .Values.persistence.storageClassName }}
  {{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.volumeName }}
  volumeName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
{{- end }} 