{{- if .Values.dockerHub.login }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhubcreds
  labels:
    app.kubernetes.io/name: {{ template "octopus.name" . }}
    helm.sh/chart: {{ template "octopus.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: {{.Values.dockerHub.creds}}
type: kubernetes.io/dockerconfigjson
{{- end }}