{{- if .Values.dockerHub.login }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhubcreds
  labels:
    {{- include "labels" . | nindent 4 }} 
data:
  .dockerconfigjson: {{.Values.dockerHub.creds}}
type: kubernetes.io/dockerconfigjson
{{- end }}