{{- if .Values.octopus.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ template "octopus.name" . }}
    helm.sh/chart: {{ template "octopus.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ template "octopus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "octopus.serviceAccountName" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "octopus.fullname" . }}
{{- end }}