{{- if .Values.octopus.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ template "octopus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "octopus.serviceAccountName" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "octopus.fullname" . }}
{{- end }}