{{- if .Values.octopus.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ template "octopus.fullname" . }}
rules:
{{ toYaml .Values.octopus.rbac.role.rules }}
{{- end }}