{{- if .Values.octopus.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.octopus.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- if .Values.octopus.serviceAccount.labels }}
    {{- toYaml .Values.octopus.serviceAccount.labels | nindent 4 }}
    {{- end }}
  name: {{ template "octopus.serviceAccountName" . }}
automountServiceAccountToken: {{ .Values.octopus.serviceAccount.automountServiceAccountToken }}
{{- end -}}