apiVersion: v1
kind: Service
metadata:
  name: {{ template "octopus.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.octopus.service.type }}
  selector:
    {{- include "octopus.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: {{.Values.octopus.webPort}}
      targetPort: 8080
      protocol: TCP
  {{- if (eq (.Values.octopus.replicaCount | int) 1)}} # If there is only one node, expose the tentacle along with the web port
    - name: tentacle
      port: {{.Values.octopus.tentaclePort}}
      targetPort: 10943
      protocol: TCP
  {{- end }}
  {{- if (gt (.Values.octopus.replicaCount | int) 1)}}
  {{- range untilStep 0 (.Values.octopus.replicaCount | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: octopus-deploy-node{{ . }}
  labels:
    {{ include "labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.octopus.service.type }}
  ports:
    - name: web
      port: {{$.Values.octopus.webPort}}
      targetPort: 8080
      protocol: TCP
    - name: tentacle
      port: {{$.Values.octopus.tentaclePort}}
      targetPort: 10943
      protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "octopus.fullname" $ }}-{{ . }}
{{- end }}
{{- end }}