kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "mssql.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y
    
    [coredump]
    captureminiandfull = true
    coredumptype = full
    
    [hadr]
    hadrenabled = 1
    
    [language]
    lcid = 1033
  