apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  sa_password : {{ .Values.SA_PASSWORD | b64enc | quote}}