{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  sa_password : {{ include "mssql.password" . | b64enc | quote}} 
{{- end }}