apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mssql.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mssql.fullname" . }}
  replicas: {{ .Values.replicas | default 1}}
  selector:
    matchLabels:
      {{- include "mssql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mssql.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/bash
            - -c
            - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
           - containerPort: {{ .Values.containers.ports.containerPort}}
          env:
            - name: MSSQL_PID
              value: "{{ .Values.MSSQL_PID}}"
            - name: ACCEPT_EULA
              value: "{{ .Values.ACCEPT_EULA | upper}}"
            - name: MSSQL_AGENT_ENABLED
              value: "{{ .Values.MSSQL_AGENT_ENABLED}}"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.createSecrets }}
                  name: {{ include "mssql.name" . }}
                  key: sa_password
                  {{- else }}
                  name: {{ .Release.Name }}-sapassword
                  key: secret
                  {{- end }}
          volumeMounts:
            - name: mssql
              mountPath: "/var/opt/mssql"
            - name: mssql-config-volume
              mountPath: /var/opt/config
      volumes:        
      - name: mssql-config-volume
        configMap:
          name: {{ include "mssql.name" . }}
  volumeClaimTemplates:
    - metadata:
        name: mssql
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if (include "mssql.storageClass" .) }}
        storageClassName: {{ include "mssql.storageClass" . }}
        {{- end }}
        resources:
          requests:
            storage: 8Gi