image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  tag: "2022-latest"

MSSQL_PID: "Developer"
MSSQL_AGENT_ENABLED: "false"

containers:
  ports:
    containerPort: 1433

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext: 
  runAsUser: 10001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add: 
      - NET_BIND_SERVICE

service:
  port: 1433

serviceAccount:
  create: true
  automountServiceAccountToken: false
  annotations: {}
  labels: {}