name: Run helm tests on Kubernetes Agent

on:
  push:
    paths:
    - charts/kubernetes-agent/**
    - .github/workflows/kubernetes-agent-tests.yaml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Helm

      uses: azure/setup-helm@v3
      with:
        version: v3.13.2

    - name: Run Helm unit tests
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest.git
        helm unittest charts/kubernetes-agent

  check-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
    - uses: docker
    - name: Generate docs 
      run: "npm run generate-agent-docs"
    - name: Check readme is unchanged 
      run: |
        echo "Ensuring readme is up-to-date"
        echo "If this test fails, run 'npm run generate-agent-docs' locally and commit the changes"
        git diff --exit-code