name: "Kubernetes Target - Build and Publish"

on:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./charts/kubernetes-tentacle
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4
